apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.express.name }}
  labels:
    app: {{ .Values.express.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.express.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.express.name }}
    spec:
      containers:
      - name: {{ .Values.express.name }}
        image: {{ .Values.express.image }}
        ports:
        - containerPort: {{ .Values.express.port }}
        envFrom:
          - configMapRef:
              name: express-configmap
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: secret
                key: username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: password