apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flask.name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.flask.name }}
  ports:
    - port: {{ .Values.flask.port }}
      targetPort: {{ .Values.flask.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.mongo.name }}
  ports:
    - port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.express.name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.express.name }}
  ports:
    - port: {{ .Values.express.port }}
      targetPort: {{ .Values.express.port }}